=== EliotCoIe/website/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="restaurant">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="streetAddress" type="xs:string"/>
                            <xs:element name="addressLocality" type="xs:string"/>
                            <xs:element name="addressCountry" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="phone" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="menu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="price" type="xs:string"/>
                                        <xs:element name="type" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="reservation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="table" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:integer"/>
                                        <xs:element name="capacity" type="xs:integer"/>
                                        <xs:element name="location" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="chef" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="specialty" type="xs:string"/>
                            <xs:element name="experience" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="priceType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+\.\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Regex in order to provide valid price value (2 digits before and after point) -->

    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="price" type="priceType"/>
                            <xs:element name="type" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- At least 1 year of experience required -->

    <xs:element name="experience">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- table capacity is in range from 1 to 10 -->

    <xs:element name="capacity">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="10"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- Regex in order to provide valid email format -->
    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- type element in menu can be eiter appetizer, entree or dessert -->

    <xs:element name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="appetizer"/>
                <xs:enumeration value="entree"/>
                <xs:enumeration value="dessert"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== EliotCoIe/website/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transformation.xslt"?>
<restaurant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="schema.xsd">
    <name>Voyage Restaurant</name>
    <address>
        <streetAddress>na Jiřáku 29</streetAddress>
        <addressLocality>Praha 3</addressLocality>
        <addressCountry>Czech Republic</addressCountry>
    </address>
    <phone>+420 888 333 222</phone>
    <email>info@voyagerestaurant.com</email>
    <menu>
        <item>
            <name>Soupe à l`oignon</name>
            <description>Our traditional French soup made of beef stock, onions, and served with croutons and melted cheese on the side</description>
            <price>120 czk</price>
            <type>Appetizer</type>
        </item>
        <item>
            <name>Beef bourguignon</name>
            <description>Slow cooked beef in a red wine sauce with onions, mushrooms, and bacon lardons</description>
            <price>340 czk</price>
            <type>Main Course</type>
        </item>
        <item>
            <name>Ratatouille</name>
            <description>Our seasonal vegetable stew with homemade sauce</description>
            <price>210 czk</price>
            <type>Main Course</type>
        </item>
        <item>
            <name>Chocolate soufflé</name>
            <description>Exquisite French dessert that combines dark chocolate with a creamy egg yolk base and fluffy egg whites</description>
            <price>110 czk</price>
            <type>Dessert</type>
        </item>
        <item>
            <name>Moules Frites</name>
            <description>Classic French dish of mussels cooked with white wine and served with fries</description>
            <price>260 czk</price>
            <type>Main Course</type>
        </item>
    </menu>
    <reservation>
        <table>
            <id>1</id>
            <capacity>8</capacity>
            <location>Public Room</location>
        </table>
        <table>
            <id>2</id>
            <capacity>3</capacity>
            <location>Fireplace Corner</location>
        </table>
        <table>
            <id>3</id>
            <capacity>5</capacity>
            <location>Private Zone</location>
        </table>
    </reservation>
    <chef>
        <name>Roman Kopp</name>
        <specialty>French cuisine</specialty>
        <experience>19</experience>
    </chef>
    <chef>
        <name>baby Kopp</name>
        <specialty>sese cuisine</specialty>
        <experience>5</experience>
    </chef>
</restaurant>
